// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package users

import (
	"context"

	"go-rest/zero/rpc/user/types/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserRequest  = pb.UserRequest
	UserResponse = pb.UserResponse

	Users interface {
		GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	}

	defaultUsers struct {
		cli zrpc.Client
	}
)

func NewUsers(cli zrpc.Client) Users {
	return &defaultUsers{
		cli: cli,
	}
}

func (m *defaultUsers) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := pb.NewUsersClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
