
---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: go-rest           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: go-rest        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: go-rest 
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: go-rest
        image: sansayin/goapp:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081  # Should match the port number that the Go application listens on
        
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: go-rest-service   # Name of the resource
spec:
  type: LoadBalancer                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
   - port: 8081
  selector:
    app: go-rest         # Map any pod with label `app=go-rest` to this service
