kind: Pod
apiVersion: v1
metadata:
  name: zero-1 
  labels:
    app: zero
spec:
  containers:
  - name: zero-api
    image: sansayin/zero-app:latest 
---
kind: Pod
apiVersion: v1
metadata:
  name: zero-2 
  labels:
    app: zero 
spec:
  containers:
  - name: zero-api 
    image: sansayin/zero-app:latest 
---
kind: Service
apiVersion: v1
metadata:
  name: zero-rest-service
spec:
  type: LoadBalancer
  selector:
    app: zero 
  ports:
  # Default port used by the image
  - port: 8888 
