// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"go-rest/zero/rpc/user/internal/logic"
	"go-rest/zero/rpc/user/internal/svc"
	"go-rest/zero/rpc/user/types/pb"
)

type UsersServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsersServer
}

func NewUsersServer(svcCtx *svc.ServiceContext) *UsersServer {
	return &UsersServer{
		svcCtx: svcCtx,
	}
}

func (s *UsersServer) GetUser(ctx context.Context, in *pb.UserRequest) (*pb.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
