// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"go-rest/rpc/internal/logic"
	"go-rest/rpc/internal/svc"
	"go-rest/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *pb.UserRequest) (*pb.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) GetAllUsers(ctx context.Context, in *pb.Empty) (*pb.ListResponse, error) {
	l := logic.NewGetAllUsersLogic(ctx, s.svcCtx)
	return l.GetAllUsers(in)
}

func (s *UserServer) CreateUser(ctx context.Context, in *pb.UserInfo) (*pb.UserResponse, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServer) UpdateUser(ctx context.Context, in *pb.UserInfo) (*pb.UserResponse, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}
