// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-rest/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:id",
				Handler: getUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/users",
				Handler: getUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user",
				Handler: addUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user",
				Handler: updateUserHandler(serverCtx),
			},
		},
	)
}
