info:
  contact: {}
paths:
  /users:
    delete:
      consumes:
      - '*/*'
      description: et the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Delete User By ID.
      tags:
      - users
    get:
      consumes:
      - '*/*'
      description: Get All Users from server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get All User.
      tags:
      - users
    post:
      consumes:
      - '*/*'
      description: Create User.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create User.
      tags:
      - users
  /users/:id:
    get:
      consumes:
      - '*/*'
      description: Get User Info By ID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get User By ID.
      tags:
      - users
    put:
      consumes:
      - '*/*'
      description: Update User info By ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update User By ID.
      tags:
      - users
swagger: "2.0"
