// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"go-rest/rpc/internal/logic"
	"go-rest/rpc/internal/svc"
	"go-rest/rpc/pb"
)

type UsersServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsersServer
}

func NewUsersServer(svcCtx *svc.ServiceContext) *UsersServer {
	return &UsersServer{
		svcCtx: svcCtx,
	}
}

func (s *UsersServer) GetUser(ctx context.Context, in *pb.UserRequest) (*pb.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UsersServer) GetAllUsers(ctx context.Context, in *pb.Empty) (*pb.ListResponse, error) {
	l := logic.NewGetAllUsersLogic(ctx, s.svcCtx)
	return l.GetAllUsers(in)
}

func (s *UsersServer) CreateUser(ctx context.Context, in *pb.UserInfo) (*pb.UserResponse, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UsersServer) UpdateUser(ctx context.Context, in *pb.UserInfo) (*pb.UserResponse, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}
